### PR TITLE
Add ivy-nixos-options as alternative to helm-nixos-options

### PR DESCRIPTION
**Pull request by Melkor333**
As the title says. Since I don't like the big dependency of Helm I created an [ivy](https://github.com/abo-abo/swiper) alternative.

I already added a badge URL so if this gets merged I will create a PR in the melpa repository :)

### CODE REVIEW

**Review by Atemu — APPROVED** [review]
Works just as expected, thank you!

You should probably squash your commits, not much point in keeping them separate IMO.

**Comment by alex-robbins** [comment]
It looks like this was approved but never merged. Are there still plans to merge this?

**Comment by Melkor333** [comment]
@travisbhartwell is there a certain reason for not reviewing/merging this and other PRs? It would be great to have these changes in the melpa for others to use.

If you e.g. lost interest in NixOS and don't want to keep maintaining this package, I would like to check with the NixOS community if it's possible to add this repo to the https://github.com/NixOS/ namespace. I'd make an additional note in the README to give proper credits :)

**Comment by benley** [comment]
> @travisbhartwell is there a certain reason for not reviewing/merging this and other PRs? It would be great to have these changes in the melpa for others to use.
> 
> If you e.g. lost interest in NixOS and don't want to keep maintaining this package, I would like to check with the NixOS community if it's possible to add this repo to the https://github.com/NixOS/ namespace. I'd make an additional note in the README to give proper credits :)

I'm working on getting this repo added to [nix-community](https://github.com/nix-community) in the next few days :-)

**Pull request merged**
