### PR TITLE
Shell quote args within bash -c '...'

### LINKED ISSUE #44: nix-shell-command might need to do more complicated processing? (suggested flycheck config fails on elisp files)
The readme suggests this configuration for flycheck wrappers to find nix shells:

```elisp
(setq flycheck-command-wrapper-function
        (lambda (command) (apply 'nix-shell-command (nix-current-sandbox) command))
      flycheck-executable-find
        (lambda (cmd) (nix-executable-find (nix-current-sandbox) cmd)))
```

This has been working great for my Haskell development. But when I edit an elisp file (such as ~/.emacs.d/init.el) I get this error:

> Suspicious state from syntax checker emacs-lisp-checkdoc: Flycheck checker emacs-lisp-checkdoc returned non-zero exit code 1, but its output contained no errors: /run/current-system/sw/bin/bash: -c: line 0: syntax error near unexpected token `('

The command its running appears to be this:

> "bash" "-c" "source /tmp/nix-sandbox-rc-8480dqC; /nix/store/1v2ral91bd58w3rawxb1p4a6dwdmz1fd-emacs-25.3/bin/.emacs-wrapped -Q --batch --eval (progn (setq-default sentence-end-double-space t)) --eval (progn (defvar jka-compr-inhibit) (unwind-protect (let ((jka-compr-inhibit t)) (when (equal (car command-line-args-left) \"--\") (setq command-line-args-left (cdr command-line-args-left))) (unless (require 'elisp-mode nil 'no-error) (require 'lisp-mode)) (require 'checkdoc) (let ((source (car command-line-args-left)) (process-default-directory default-directory)) (with-temp-buffer (insert-file-contents source 'visit) (setq buffer-file-name source) (setq default-directory process-default-directory) (with-demoted-errors \"Error in checkdoc: %S\" (delay-mode-hooks (emacs-lisp-mode)) (setq delayed-mode-hooks nil) (checkdoc-current-buffer t) (with-current-buffer checkdoc-diagnostic-buffer (princ (buffer-substring-no-properties (point-min) (point-max))) (kill-buffer)))))) (setq command-line-args-left nil))) -- /tmp/flycheck8480q0I/foo.el"

The problem being that quotes have been added around all the outer strings, but since we're calling bash -c the last string is another bash command, and the arguments inside that command aren't quoted properly.

I *think* what's going on is that `nix-shell-command` is taking a list of shell parameters in `command`, and in order to embed them into a bash command that sources the sandbox environment it's pasting them in a string. That works provided all the arguments are "simple" enough, but the emacs-lisp checker wants to invoke emacs with a bunch of lisp code as `--eval` arguments; all the parentheses and single quotes in the lisp arguments are being interpreted as bash syntax.

### PR DESCRIPTION
**Pull request by benley**
Fixes #44, hopefully.

### CODE REVIEW

**Comment by svenkeidel** [comment]
I take a look at your PR later today. Thank you for your contribution.

**Comment by benley** [comment]
Ping?

**Comment by bb010g** [comment]
bump

**Comment by benley** [comment]
Friendly ping - I believe this is still relevant.

**Comment by benley** [comment]
Is there any chance of getting this merged at some point?

Also, would you like a hand with maintaining this repository in general?

**Comment by DamienCassou** [comment]
I'm also interested in having this merged.

**Comment by travisbhartwell** [comment]
@benley Yes I would. As you can see, I've kind of forgotten about this. I don't use NixOS heavily in my day to day and don't have much time for open source work.

I'm interested in:
- help with the repo

Or, more appropriately,
- seeing if ownership of this can be moved under the Nix org and maintained there.

For now, I'll add you, but I would welcome any help towards the latter so I don't block others.

**Pull request merged**
